Repository 8devices/wakaama, pull requests merged in 2018-04, with the labels that each got.

#50 core: remove client transactions when freeing it
  core/internals.h
  core/liblwm2m.c
  core/registration.c
  core/transaction.c
Labels: bug

#56 Prevent new emulator unhandled promises by using previous version
  tests-rest/package.json
Labels: bug

#55 Add command line arguments reading and logging module
  examples/rest-server/CMakeLists.txt
  examples/rest-server/logging.c
  examples/rest-server/logging.h
  examples/rest-server/rest-core.c
  examples/rest-server/rest-notifications.c
  examples/rest-server/rest-resources.c
  examples/rest-server/rest-subscriptions.c
  examples/rest-server/restserver.c
Labels: enhancement

#57 Implement configuration reading, move argument parsing to separate module
  examples/rest-server/CMakeLists.txt
  examples/rest-server/restserver.c
  examples/rest-server/settings.c
  examples/rest-server/settings.h
Labels: enhancement

#59 Fix callback issues
  examples/rest-server/rest-core.c
  examples/rest-server/rest-notifications.c
  examples/rest-server/restserver.c
  examples/rest-server/restserver.h
  tests-rest/notifications.spec.js
Labels: not-as-expected

#58 Update documentation
  examples/rest-server/README.md
  examples/rest-server/RESTAPI.md
Labels: informational
